#!/bin/bash

# Tell rtplugs that we use CGO
export CGO_ENABLED=1

# List of all supported plug packages (comma seperated)
RTPLUGS_PKG="github.com/IBM/go-security-plugs/plugs/rtgate,github.com/IBM/go-security-plugs/plugs/wsgate"

# Tel RTPLUGS which plugs to activate (comma seperated)
export RTPLUGS="wsgate,rtgate"

# cleanup static imports if any
rm -rf auto_generate_imports.go

# Create so files from plug packages
MYSOS=""
IFS="," read -r -a PKG_ARRAY <<< ${RTPLUGS_PKG}
for p in ${PKG_ARRAY}
do
# process
echo "Processing ${p}"

PKG_NAME=${p##*/}
echo "Processing ${PKG_NAME}"
GODIR="plugs_so/${PKG_NAME}"
GOFILE="${GODIR}/${PKG_NAME}.go"
SOFILE="${GODIR}/${PKG_NAME}.so"
mkdir -p "${GODIR}"

cat <<EOT > ${GOFILE}
// Code auto-generated by ${0}. DO NOT EDIT.

package main
import _ "${p}"
EOT


go build -buildmode=plugin -o ${SOFILE}  ${GOFILE} 
if [ $? -eq 0 ]; then
    echo "${SOFILE} was created" 
    if [ -z "${MYSOS}" ]
    then
        MYSOS=${SOFILE}
    else
        MYSOS="$MYSOS,${SOFILE}"
    fi 
    
else
    echo "FAIL: ${SOFILE} was not created!"
fi
    
done

#echo "------------------------"
#MYSOS=""
#echo "Build plugs_so:"
#for dir in plugs_so/*/     # list directories in the form "/tmp/dirname/"
#do
#    PKG_NAME=${p##*/}
#    echo "Processing ${PKG_NAME} in ${dir}"
#    cd "${dir}"
#    go build -buildmode=plugin   . 
#    if [ $? -eq 0 ]; then
#        echo "so file was created in ${dir}${PKG_NAME}.so"
#        if [ -z "${MYSOS}" ]
#        then
#            MYSOS="${dir}${PKG_NAME}.so"
#        else
#            MYSOS="$MYSOS ${dir}${PKG_NAME}.so"
#        fi 
#        
#    else
#        echo "FAIL: so file was not created in ${dir}"
#    fi
#    cd ../..
#done


# Tel RTPLUGS which so plugs to load (comma seperated)
export RTPLUGS_SO=${MYSOS}
echo "exported RTPLUGS_SO=${RTPLUGS_SO}"

echo "------------------------"
echo "Run Proxy with dynamic plugs"
go run .

