// Code generated by ./hack/add_queue_options.sh. DO NOT EDIT.
package main

import "os"

import "github.com/IBM/go-security-plugs/qpsecurity"
import "knative.dev/serving/pkg/queue/sharedmain"

import _ "github.com/IBM/go-security-plugs/plugs/testgate"
func main() {
    os.Setenv("RTPLUGS", "testgate")

    qOpt := qpsecurity.NewQPSecurityPlugs()
    defer qOpt.Shutdown()

    sharedmain.Main(qOpt.Setup)
}